// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.g.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PigeonFirebaseApp ()
+ (PigeonFirebaseApp *)fromList:(NSArray *)list;
+ (nullable PigeonFirebaseApp *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PigeonStorageReference ()
+ (PigeonStorageReference *)fromList:(NSArray *)list;
+ (nullable PigeonStorageReference *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PigeonFullMetaData ()
+ (PigeonFullMetaData *)fromList:(NSArray *)list;
+ (nullable PigeonFullMetaData *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PigeonListOptions ()
+ (PigeonListOptions *)fromList:(NSArray *)list;
+ (nullable PigeonListOptions *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PigeonSettableMetadata ()
+ (PigeonSettableMetadata *)fromList:(NSArray *)list;
+ (nullable PigeonSettableMetadata *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation PigeonFirebaseApp
+ (instancetype)makeWithAppName:(NSString *)appName
    tenantId:(nullable NSString *)tenantId {
  PigeonFirebaseApp* pigeonResult = [[PigeonFirebaseApp alloc] init];
  pigeonResult.appName = appName;
  pigeonResult.tenantId = tenantId;
  return pigeonResult;
}
+ (PigeonFirebaseApp *)fromList:(NSArray *)list {
  PigeonFirebaseApp *pigeonResult = [[PigeonFirebaseApp alloc] init];
  pigeonResult.appName = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.appName != nil, @"");
  pigeonResult.tenantId = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PigeonFirebaseApp *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonFirebaseApp fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.appName ?: [NSNull null]),
    (self.tenantId ?: [NSNull null]),
  ];
}
@end

@implementation PigeonStorageReference
+ (instancetype)makeWithBucket:(NSString *)bucket
    fullPath:(NSString *)fullPath
    name:(NSString *)name {
  PigeonStorageReference* pigeonResult = [[PigeonStorageReference alloc] init];
  pigeonResult.bucket = bucket;
  pigeonResult.fullPath = fullPath;
  pigeonResult.name = name;
  return pigeonResult;
}
+ (PigeonStorageReference *)fromList:(NSArray *)list {
  PigeonStorageReference *pigeonResult = [[PigeonStorageReference alloc] init];
  pigeonResult.bucket = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.bucket != nil, @"");
  pigeonResult.fullPath = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.fullPath != nil, @"");
  pigeonResult.name = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.name != nil, @"");
  return pigeonResult;
}
+ (nullable PigeonStorageReference *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonStorageReference fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.bucket ?: [NSNull null]),
    (self.fullPath ?: [NSNull null]),
    (self.name ?: [NSNull null]),
  ];
}
@end

@implementation PigeonFullMetaData
+ (instancetype)makeWithMetadata:(nullable NSDictionary<NSString *, id> *)metadata {
  PigeonFullMetaData* pigeonResult = [[PigeonFullMetaData alloc] init];
  pigeonResult.metadata = metadata;
  return pigeonResult;
}
+ (PigeonFullMetaData *)fromList:(NSArray *)list {
  PigeonFullMetaData *pigeonResult = [[PigeonFullMetaData alloc] init];
  pigeonResult.metadata = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable PigeonFullMetaData *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonFullMetaData fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.metadata ?: [NSNull null]),
  ];
}
@end

@implementation PigeonListOptions
+ (instancetype)makeWithMaxResults:(nullable NSNumber *)maxResults
    pageToken:(nullable NSString *)pageToken {
  PigeonListOptions* pigeonResult = [[PigeonListOptions alloc] init];
  pigeonResult.maxResults = maxResults;
  pigeonResult.pageToken = pageToken;
  return pigeonResult;
}
+ (PigeonListOptions *)fromList:(NSArray *)list {
  PigeonListOptions *pigeonResult = [[PigeonListOptions alloc] init];
  pigeonResult.maxResults = GetNullableObjectAtIndex(list, 0);
  pigeonResult.pageToken = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PigeonListOptions *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonListOptions fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.maxResults ?: [NSNull null]),
    (self.pageToken ?: [NSNull null]),
  ];
}
@end

@implementation PigeonSettableMetadata
+ (instancetype)makeWithCacheControl:(nullable NSString *)cacheControl
    contentDisposition:(nullable NSString *)contentDisposition
    contentEncoding:(nullable NSString *)contentEncoding
    contentLanguage:(nullable NSString *)contentLanguage
    contentType:(nullable NSString *)contentType
    customMetadata:(nullable NSDictionary<NSString *, NSString *> *)customMetadata {
  PigeonSettableMetadata* pigeonResult = [[PigeonSettableMetadata alloc] init];
  pigeonResult.cacheControl = cacheControl;
  pigeonResult.contentDisposition = contentDisposition;
  pigeonResult.contentEncoding = contentEncoding;
  pigeonResult.contentLanguage = contentLanguage;
  pigeonResult.contentType = contentType;
  pigeonResult.customMetadata = customMetadata;
  return pigeonResult;
}
+ (PigeonSettableMetadata *)fromList:(NSArray *)list {
  PigeonSettableMetadata *pigeonResult = [[PigeonSettableMetadata alloc] init];
  pigeonResult.cacheControl = GetNullableObjectAtIndex(list, 0);
  pigeonResult.contentDisposition = GetNullableObjectAtIndex(list, 1);
  pigeonResult.contentEncoding = GetNullableObjectAtIndex(list, 2);
  pigeonResult.contentLanguage = GetNullableObjectAtIndex(list, 3);
  pigeonResult.contentType = GetNullableObjectAtIndex(list, 4);
  pigeonResult.customMetadata = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable PigeonSettableMetadata *)nullableFromList:(NSArray *)list {
  return (list) ? [PigeonSettableMetadata fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.cacheControl ?: [NSNull null]),
    (self.contentDisposition ?: [NSNull null]),
    (self.contentEncoding ?: [NSNull null]),
    (self.contentLanguage ?: [NSNull null]),
    (self.contentType ?: [NSNull null]),
    (self.customMetadata ?: [NSNull null]),
  ];
}
@end

@interface FirebaseStorageHostApiCodecReader : FlutterStandardReader
@end
@implementation FirebaseStorageHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PigeonFirebaseApp fromList:[self readValue]];
    case 129: 
      return [PigeonStorageReference fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FirebaseStorageHostApiCodecWriter : FlutterStandardWriter
@end
@implementation FirebaseStorageHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PigeonFirebaseApp class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PigeonStorageReference class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FirebaseStorageHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FirebaseStorageHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FirebaseStorageHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FirebaseStorageHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FirebaseStorageHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FirebaseStorageHostApiCodecReaderWriter *readerWriter = [[FirebaseStorageHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void FirebaseStorageHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FirebaseStorageHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageHostApi.getReferencebyPath"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getReferencebyPathApp:path:error:)], @"FirebaseStorageHostApi api (%@) doesn't respond to @selector(getReferencebyPathApp:path:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSString *arg_path = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        PigeonStorageReference *output = [api getReferencebyPathApp:arg_app path:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageHostApi.setMaxOperationRetryTime"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMaxOperationRetryTimeApp:time:error:)], @"FirebaseStorageHostApi api (%@) doesn't respond to @selector(setMaxOperationRetryTimeApp:time:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_time = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setMaxOperationRetryTimeApp:arg_app time:arg_time error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageHostApi.setMaxUploadRetryTime"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMaxUploadRetryTimeApp:time:error:)], @"FirebaseStorageHostApi api (%@) doesn't respond to @selector(setMaxUploadRetryTimeApp:time:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_time = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setMaxUploadRetryTimeApp:arg_app time:arg_time error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageHostApi.setMaxDownloadRetryTime"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMaxDownloadRetryTimeApp:time:error:)], @"FirebaseStorageHostApi api (%@) doesn't respond to @selector(setMaxDownloadRetryTimeApp:time:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_time = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setMaxDownloadRetryTimeApp:arg_app time:arg_time error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageHostApi.useStorageEmulator"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(useStorageEmulatorApp:host:port:completion:)], @"FirebaseStorageHostApi api (%@) doesn't respond to @selector(useStorageEmulatorApp:host:port:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSString *arg_host = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_port = GetNullableObjectAtIndex(args, 2);
        [api useStorageEmulatorApp:arg_app host:arg_host port:arg_port completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FirebaseStorageReferenceHostApiCodecReader : FlutterStandardReader
@end
@implementation FirebaseStorageReferenceHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PigeonFirebaseApp fromList:[self readValue]];
    case 129: 
      return [PigeonFullMetaData fromList:[self readValue]];
    case 130: 
      return [PigeonListOptions fromList:[self readValue]];
    case 131: 
      return [PigeonSettableMetadata fromList:[self readValue]];
    case 132: 
      return [PigeonStorageReference fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FirebaseStorageReferenceHostApiCodecWriter : FlutterStandardWriter
@end
@implementation FirebaseStorageReferenceHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PigeonFirebaseApp class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PigeonFullMetaData class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PigeonListOptions class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PigeonSettableMetadata class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PigeonStorageReference class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FirebaseStorageReferenceHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FirebaseStorageReferenceHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FirebaseStorageReferenceHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FirebaseStorageReferenceHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FirebaseStorageReferenceHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FirebaseStorageReferenceHostApiCodecReaderWriter *readerWriter = [[FirebaseStorageReferenceHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void FirebaseStorageReferenceHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FirebaseStorageReferenceHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getParent"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getParentApp:error:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getParentApp:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        PigeonStorageReference *output = [api getParentApp:arg_app error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getRoot"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getRootApp:error:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getRootApp:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        PigeonStorageReference *output = [api getRootApp:arg_app error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getChild"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getChildApp:path:error:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getChildApp:path:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSString *arg_path = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        PigeonStorageReference *output = [api getChildApp:arg_app path:arg_path error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.delete"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(deleteApp:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(deleteApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api deleteApp:arg_app completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getDownloadURL"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDownloadURLApp:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getDownloadURLApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api getDownloadURLApp:arg_app completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getMetaData"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMetaDataApp:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getMetaDataApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api getMetaDataApp:arg_app completion:^(PigeonFullMetaData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.list"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(listApp:options:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(listApp:options:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        PigeonListOptions *arg_options = GetNullableObjectAtIndex(args, 1);
        [api listApp:arg_app options:arg_options completion:^(NSArray<PigeonStorageReference *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.listAll"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(listAllApp:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(listAllApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api listAllApp:arg_app completion:^(NSArray<PigeonStorageReference *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.getData"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDataApp:maxSize:error:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(getDataApp:maxSize:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_maxSize = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        NSArray<NSNumber *> *output = [api getDataApp:arg_app maxSize:arg_maxSize error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageReferenceHostApi.updateMetadata"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageReferenceHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updateMetadataApp:metadata:completion:)], @"FirebaseStorageReferenceHostApi api (%@) doesn't respond to @selector(updateMetadataApp:metadata:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        PigeonSettableMetadata *arg_metadata = GetNullableObjectAtIndex(args, 1);
        [api updateMetadataApp:arg_app metadata:arg_metadata completion:^(PigeonFullMetaData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FirebaseStorageTaskHostApiCodecReader : FlutterStandardReader
@end
@implementation FirebaseStorageTaskHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PigeonFirebaseApp fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FirebaseStorageTaskHostApiCodecWriter : FlutterStandardWriter
@end
@implementation FirebaseStorageTaskHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PigeonFirebaseApp class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FirebaseStorageTaskHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FirebaseStorageTaskHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FirebaseStorageTaskHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FirebaseStorageTaskHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FirebaseStorageTaskHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FirebaseStorageTaskHostApiCodecReaderWriter *readerWriter = [[FirebaseStorageTaskHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void FirebaseStorageTaskHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FirebaseStorageTaskHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageTaskHostApi.pause"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageTaskHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseApp:completion:)], @"FirebaseStorageTaskHostApi api (%@) doesn't respond to @selector(pauseApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api pauseApp:arg_app completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageTaskHostApi.resume"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageTaskHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resumeApp:completion:)], @"FirebaseStorageTaskHostApi api (%@) doesn't respond to @selector(resumeApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api resumeApp:arg_app completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FirebaseStorageTaskHostApi.cancel"
        binaryMessenger:binaryMessenger
        codec:FirebaseStorageTaskHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(cancelApp:completion:)], @"FirebaseStorageTaskHostApi api (%@) doesn't respond to @selector(cancelApp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        PigeonFirebaseApp *arg_app = GetNullableObjectAtIndex(args, 0);
        [api cancelApp:arg_app completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
