// Autogenerated from Pigeon (v3.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.flutter.plugins.firebase.auth;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class GeneratedAndroidFirebaseAuth {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PigeonMultiFactorSession {
    private @NonNull String id;
    public @NonNull String getId() { return id; }
    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** Constructor is private to enforce null safety; use Builder. */
    private PigeonMultiFactorSession() {}
    public static final class Builder {
      private @Nullable String id;
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }
      public @NonNull PigeonMultiFactorSession build() {
        PigeonMultiFactorSession pigeonReturn = new PigeonMultiFactorSession();
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("id", id);
      return toMapResult;
    }
    static @NonNull PigeonMultiFactorSession fromMap(@NonNull Map<String, Object> map) {
      PigeonMultiFactorSession pigeonResult = new PigeonMultiFactorSession();
      Object id = map.get("id");
      pigeonResult.setId((String)id);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PigeonPhoneMultiFactorAssertion {
    private @NonNull String verificationId;
    public @NonNull String getVerificationId() { return verificationId; }
    public void setVerificationId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"verificationId\" is null.");
      }
      this.verificationId = setterArg;
    }

    private @NonNull String verificationCode;
    public @NonNull String getVerificationCode() { return verificationCode; }
    public void setVerificationCode(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"verificationCode\" is null.");
      }
      this.verificationCode = setterArg;
    }

    /** Constructor is private to enforce null safety; use Builder. */
    private PigeonPhoneMultiFactorAssertion() {}
    public static final class Builder {
      private @Nullable String verificationId;
      public @NonNull Builder setVerificationId(@NonNull String setterArg) {
        this.verificationId = setterArg;
        return this;
      }
      private @Nullable String verificationCode;
      public @NonNull Builder setVerificationCode(@NonNull String setterArg) {
        this.verificationCode = setterArg;
        return this;
      }
      public @NonNull PigeonPhoneMultiFactorAssertion build() {
        PigeonPhoneMultiFactorAssertion pigeonReturn = new PigeonPhoneMultiFactorAssertion();
        pigeonReturn.setVerificationId(verificationId);
        pigeonReturn.setVerificationCode(verificationCode);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("verificationId", verificationId);
      toMapResult.put("verificationCode", verificationCode);
      return toMapResult;
    }
    static @NonNull PigeonPhoneMultiFactorAssertion fromMap(@NonNull Map<String, Object> map) {
      PigeonPhoneMultiFactorAssertion pigeonResult = new PigeonPhoneMultiFactorAssertion();
      Object verificationId = map.get("verificationId");
      pigeonResult.setVerificationId((String)verificationId);
      Object verificationCode = map.get("verificationCode");
      pigeonResult.setVerificationCode((String)verificationCode);
      return pigeonResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class MultiFactorUserHostApiCodec extends StandardMessageCodec {
    public static final MultiFactorUserHostApiCodec INSTANCE = new MultiFactorUserHostApiCodec();
    private MultiFactorUserHostApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return PigeonMultiFactorSession.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)129:         
          return PigeonPhoneMultiFactorAssertion.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof PigeonMultiFactorSession) {
        stream.write(128);
        writeValue(stream, ((PigeonMultiFactorSession) value).toMap());
      } else 
      if (value instanceof PigeonPhoneMultiFactorAssertion) {
        stream.write(129);
        writeValue(stream, ((PigeonPhoneMultiFactorAssertion) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface MultiFactorUserHostApi {
    void enrollPhone(@NonNull String appName, @NonNull PigeonPhoneMultiFactorAssertion assertion, @Nullable String displayName, Result<Void> result);
    void getSession(@NonNull String appName, Result<PigeonMultiFactorSession> result);

    /** The codec used by MultiFactorUserHostApi. */
    static MessageCodec<Object> getCodec() {
      return MultiFactorUserHostApiCodec.INSTANCE;
    }

    /** Sets up an instance of `MultiFactorUserHostApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, MultiFactorUserHostApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MultiFactorUserHostApi.enrollPhone", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String appNameArg = (String)args.get(0);
              if (appNameArg == null) {
                throw new NullPointerException("appNameArg unexpectedly null.");
              }
              PigeonPhoneMultiFactorAssertion assertionArg = (PigeonPhoneMultiFactorAssertion)args.get(1);
              if (assertionArg == null) {
                throw new NullPointerException("assertionArg unexpectedly null.");
              }
              String displayNameArg = (String)args.get(2);
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.put("result", null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.enrollPhone(appNameArg, assertionArg, displayNameArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.MultiFactorUserHostApi.getSession", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String appNameArg = (String)args.get(0);
              if (appNameArg == null) {
                throw new NullPointerException("appNameArg unexpectedly null.");
              }
              Result<PigeonMultiFactorSession> resultCallback = new Result<PigeonMultiFactorSession>() {
                public void success(PigeonMultiFactorSession result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.getSession(appNameArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
