// Copyright 2026, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.firebase.inappmessaging

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private object GeneratedAndroidFirebaseInAppMessagingPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError(
        "channel-error", "Unable to establish connection on channel: '$channelName'.", "")
  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(exception.code, exception.message, exception.details)
    } else {
      listOf(
          exception.javaClass.simpleName,
          exception.toString(),
          "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception))
    }
  }

  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null
) : RuntimeException()

/** How an in-app message was dismissed. */
enum class FiamDismissType(val raw: Int) {
  /** The message was swiped away. Only reported on iOS, for banner messages. */
  SWIPE(0),
  /** The user tapped a button to close the message. */
  CLICKED_CANCEL(1),
  /** The message was dismissed automatically. Only reported on iOS, for banner messages. */
  AUTO(2),
  /**
   * The way the message was dismissed is unknown. Always reported on Android, which does not expose
   * a dismiss type.
   */
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): FiamDismissType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Metadata of the campaign an in-app message belongs to.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FiamCampaignMetadata(
    val campaignId: String,
    val campaignName: String,
    val isTestMessage: Boolean
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FiamCampaignMetadata {
      val campaignId = pigeonVar_list[0] as String
      val campaignName = pigeonVar_list[1] as String
      val isTestMessage = pigeonVar_list[2] as Boolean
      return FiamCampaignMetadata(campaignId, campaignName, isTestMessage)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        campaignId,
        campaignName,
        isTestMessage,
    )
  }

  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FiamCampaignMetadata
    return GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepEquals(
        this.campaignId, other.campaignId) &&
        GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepEquals(
            this.campaignName, other.campaignName) &&
        GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepEquals(
            this.isTestMessage, other.isTestMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result =
        31 * result + GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepHash(this.campaignId)
    result =
        31 * result + GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepHash(this.campaignName)
    result =
        31 * result + GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepHash(this.isTestMessage)
    return result
  }
}

/**
 * The action attached to the button a user tapped on an in-app message.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FiamAction(val actionUrl: String? = null, val buttonText: String? = null) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FiamAction {
      val actionUrl = pigeonVar_list[0] as String?
      val buttonText = pigeonVar_list[1] as String?
      return FiamAction(actionUrl, buttonText)
    }
  }

  fun toList(): List<Any?> {
    return listOf(
        actionUrl,
        buttonText,
    )
  }

  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FiamAction
    return GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepEquals(
        this.actionUrl, other.actionUrl) &&
        GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepEquals(
            this.buttonText, other.buttonText)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result =
        31 * result + GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepHash(this.actionUrl)
    result =
        31 * result + GeneratedAndroidFirebaseInAppMessagingPigeonUtils.deepHash(this.buttonText)
    return result
  }
}

private open class GeneratedAndroidFirebaseInAppMessagingPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let { FiamDismissType.ofRaw(it.toInt()) }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { FiamCampaignMetadata.fromList(it) }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { FiamAction.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is FiamDismissType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is FiamCampaignMetadata -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is FiamAction -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FirebaseInAppMessagingHostApi {
  fun triggerEvent(appName: String, eventName: String, callback: (Result<Unit>) -> Unit)

  fun setMessagesSuppressed(appName: String, suppress: Boolean, callback: (Result<Unit>) -> Unit)

  fun setAutomaticDataCollectionEnabled(
      appName: String,
      enabled: Boolean,
      callback: (Result<Unit>) -> Unit
  )
  /**
   * Attaches the native message lifecycle listeners that forward events to
   * [FirebaseInAppMessagingFlutterApi]. Calling this more than once is a no-op.
   */
  fun addEventListeners(appName: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by FirebaseInAppMessagingHostApi. */
    val codec: MessageCodec<Any?> by lazy { GeneratedAndroidFirebaseInAppMessagingPigeonCodec() }
    /**
     * Sets up an instance of `FirebaseInAppMessagingHostApi` to handle messages through the
     * `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
        binaryMessenger: BinaryMessenger,
        api: FirebaseInAppMessagingHostApi?,
        messageChannelSuffix: String = ""
    ) {
      val separatedMessageChannelSuffix =
          if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingHostApi.triggerEvent$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appNameArg = args[0] as String
            val eventNameArg = args[1] as String
            api.triggerEvent(appNameArg, eventNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapError(error))
              } else {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingHostApi.setMessagesSuppressed$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appNameArg = args[0] as String
            val suppressArg = args[1] as Boolean
            api.setMessagesSuppressed(appNameArg, suppressArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapError(error))
              } else {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingHostApi.setAutomaticDataCollectionEnabled$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appNameArg = args[0] as String
            val enabledArg = args[1] as Boolean
            api.setAutomaticDataCollectionEnabled(appNameArg, enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapError(error))
              } else {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
            BasicMessageChannel<Any?>(
                binaryMessenger,
                "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingHostApi.addEventListeners$separatedMessageChannelSuffix",
                codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appNameArg = args[0] as String
            api.addEventListeners(appNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapError(error))
              } else {
                reply.reply(GeneratedAndroidFirebaseInAppMessagingPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FirebaseInAppMessagingFlutterApi(
    private val binaryMessenger: BinaryMessenger,
    private val messageChannelSuffix: String = ""
) {
  companion object {
    /** The codec used by FirebaseInAppMessagingFlutterApi. */
    val codec: MessageCodec<Any?> by lazy { GeneratedAndroidFirebaseInAppMessagingPigeonCodec() }
  }

  fun onMessageClicked(
      campaignMetadataArg: FiamCampaignMetadata,
      actionArg: FiamAction,
      callback: (Result<Unit>) -> Unit
  ) {
    val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
        "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingFlutterApi.onMessageClicked$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(campaignMetadataArg, actionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(
            Result.failure(
                GeneratedAndroidFirebaseInAppMessagingPigeonUtils.createConnectionError(
                    channelName)))
      }
    }
  }

  fun onMessageImpression(
      campaignMetadataArg: FiamCampaignMetadata,
      callback: (Result<Unit>) -> Unit
  ) {
    val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
        "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingFlutterApi.onMessageImpression$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(campaignMetadataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(
            Result.failure(
                GeneratedAndroidFirebaseInAppMessagingPigeonUtils.createConnectionError(
                    channelName)))
      }
    }
  }

  fun onMessageDismissed(
      campaignMetadataArg: FiamCampaignMetadata,
      dismissTypeArg: FiamDismissType,
      callback: (Result<Unit>) -> Unit
  ) {
    val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
        "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingFlutterApi.onMessageDismissed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(campaignMetadataArg, dismissTypeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(
            Result.failure(
                GeneratedAndroidFirebaseInAppMessagingPigeonUtils.createConnectionError(
                    channelName)))
      }
    }
  }

  fun onMessageDisplayError(
      campaignMetadataArg: FiamCampaignMetadata,
      errorMessageArg: String?,
      callback: (Result<Unit>) -> Unit
  ) {
    val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
        "dev.flutter.pigeon.firebase_in_app_messaging_platform_interface.FirebaseInAppMessagingFlutterApi.onMessageDisplayError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(campaignMetadataArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(
            Result.failure(
                GeneratedAndroidFirebaseInAppMessagingPigeonUtils.createConnectionError(
                    channelName)))
      }
    }
  }
}
