// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChANFrQztBhU1Jg86xbhhMpRY72BPpEIw',
    appId: '1:958807142248:web:902a4fb0bd5a12d7e270dd',
    messagingSenderId: '958807142248',
    projectId: 'movie-app-dart',
    authDomain: 'movie-app-dart.firebaseapp.com',
    storageBucket: 'movie-app-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkU8nvE88wqNZ4IiyNBuiXO0bZLnrZzr8',
    appId: '1:958807142248:android:65427dbcc342aa78e270dd',
    messagingSenderId: '958807142248',
    projectId: 'movie-app-dart',
    storageBucket: 'movie-app-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXv1JQMr64c7UT0GbE_s4RecrtGbqpUZE',
    appId: '1:958807142248:ios:07cd4a76219e451de270dd',
    messagingSenderId: '958807142248',
    projectId: 'movie-app-dart',
    storageBucket: 'movie-app-dart.appspot.com',
    iosClientId: '958807142248-rn8oj5p9j3257gtfh2h4bejlrscp23fq.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.dataconnect.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXv1JQMr64c7UT0GbE_s4RecrtGbqpUZE',
    appId: '1:958807142248:ios:07cd4a76219e451de270dd',
    messagingSenderId: '958807142248',
    projectId: 'movie-app-dart',
    storageBucket: 'movie-app-dart.appspot.com',
    iosClientId: '958807142248-rn8oj5p9j3257gtfh2h4bejlrscp23fq.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.dataconnect.example',
  );

}