// Copyright 2025, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FirebaseRemoteConfigRemoteConfigPigeonSettings:
 *
 */

G_DECLARE_FINAL_TYPE(FirebaseRemoteConfigRemoteConfigPigeonSettings,
                     firebase_remote_config_remote_config_pigeon_settings,
                     FIREBASE_REMOTE_CONFIG, REMOTE_CONFIG_PIGEON_SETTINGS,
                     GObject)

/**
 * firebase_remote_config_remote_config_pigeon_settings_new:
 * fetch_timeout_seconds: field in this object.
 * minimum_fetch_interval_seconds: field in this object.
 *
 * Creates a new #RemoteConfigPigeonSettings object.
 *
 * Returns: a new #FirebaseRemoteConfigRemoteConfigPigeonSettings
 */
FirebaseRemoteConfigRemoteConfigPigeonSettings*
firebase_remote_config_remote_config_pigeon_settings_new(
    int64_t fetch_timeout_seconds, int64_t minimum_fetch_interval_seconds);

/**
 * firebase_remote_config_remote_config_pigeon_settings_get_fetch_timeout_seconds
 * @object: a #FirebaseRemoteConfigRemoteConfigPigeonSettings.
 *
 * Gets the value of the fetchTimeoutSeconds field of @object.
 *
 * Returns: the field value.
 */
int64_t
firebase_remote_config_remote_config_pigeon_settings_get_fetch_timeout_seconds(
    FirebaseRemoteConfigRemoteConfigPigeonSettings* object);

/**
 * firebase_remote_config_remote_config_pigeon_settings_get_minimum_fetch_interval_seconds
 * @object: a #FirebaseRemoteConfigRemoteConfigPigeonSettings.
 *
 * Gets the value of the minimumFetchIntervalSeconds field of @object.
 *
 * Returns: the field value.
 */
int64_t
firebase_remote_config_remote_config_pigeon_settings_get_minimum_fetch_interval_seconds(
    FirebaseRemoteConfigRemoteConfigPigeonSettings* object);

/**
 * firebase_remote_config_remote_config_pigeon_settings_equals:
 * @a: a #FirebaseRemoteConfigRemoteConfigPigeonSettings.
 * @b: another #FirebaseRemoteConfigRemoteConfigPigeonSettings.
 *
 * Checks if two #FirebaseRemoteConfigRemoteConfigPigeonSettings objects are
 * equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean firebase_remote_config_remote_config_pigeon_settings_equals(
    FirebaseRemoteConfigRemoteConfigPigeonSettings* a,
    FirebaseRemoteConfigRemoteConfigPigeonSettings* b);

/**
 * firebase_remote_config_remote_config_pigeon_settings_hash:
 * @object: a #FirebaseRemoteConfigRemoteConfigPigeonSettings.
 *
 * Calculates a hash code for a #FirebaseRemoteConfigRemoteConfigPigeonSettings
 * object.
 *
 * Returns: the hash code.
 */
guint firebase_remote_config_remote_config_pigeon_settings_hash(
    FirebaseRemoteConfigRemoteConfigPigeonSettings* object);

G_DECLARE_FINAL_TYPE(FirebaseRemoteConfigMessageCodec,
                     firebase_remote_config_message_codec,
                     FIREBASE_REMOTE_CONFIG, MESSAGE_CODEC,
                     FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int firebase_remote_config_remote_config_pigeon_settings_type_id;

G_DECLARE_FINAL_TYPE(FirebaseRemoteConfigFirebaseRemoteConfigHostApi,
                     firebase_remote_config_firebase_remote_config_host_api,
                     FIREBASE_REMOTE_CONFIG, FIREBASE_REMOTE_CONFIG_HOST_API,
                     GObject)

G_DECLARE_FINAL_TYPE(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle,
    firebase_remote_config_firebase_remote_config_host_api_response_handle,
    FIREBASE_REMOTE_CONFIG, FIREBASE_REMOTE_CONFIG_HOST_API_RESPONSE_HANDLE,
    GObject)

/**
 * FirebaseRemoteConfigFirebaseRemoteConfigHostApiVTable:
 *
 * Table of functions exposed by FirebaseRemoteConfigHostApi to be implemented
 * by the API provider.
 */
typedef struct {
  void (*fetch)(const gchar* app_name,
                FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
                    response_handle,
                gpointer user_data);
  void (*fetch_and_activate)(
      const gchar* app_name,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*activate)(
      const gchar* app_name,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*set_config_settings)(
      const gchar* app_name,
      FirebaseRemoteConfigRemoteConfigPigeonSettings* settings,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*set_defaults)(
      const gchar* app_name, FlValue* default_parameters,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*ensure_initialized)(
      const gchar* app_name,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*set_custom_signals)(
      const gchar* app_name, FlValue* custom_signals,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
  void (*get_all)(const gchar* app_name,
                  FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
                      response_handle,
                  gpointer user_data);
  void (*get_properties)(
      const gchar* app_name,
      FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
          response_handle,
      gpointer user_data);
} FirebaseRemoteConfigFirebaseRemoteConfigHostApiVTable;

/**
 * firebase_remote_config_firebase_remote_config_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free
 * @user_data, or %NULL.
 *
 * Connects the method handlers in the FirebaseRemoteConfigHostApi API.
 */
void firebase_remote_config_firebase_remote_config_host_api_set_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix,
    const FirebaseRemoteConfigFirebaseRemoteConfigHostApiVTable* vtable,
    gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * firebase_remote_config_firebase_remote_config_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the FirebaseRemoteConfigHostApi API.
 */
void firebase_remote_config_firebase_remote_config_host_api_clear_method_handlers(
    FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_fetch:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 *
 * Responds to FirebaseRemoteConfigHostApi.fetch.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_fetch(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_fetch:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.fetch.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_fetch(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_fetch_and_activate:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FirebaseRemoteConfigHostApi.fetchAndActivate.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_fetch_and_activate(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    gboolean return_value);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_fetch_and_activate:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.fetchAndActivate.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_fetch_and_activate(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_activate:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FirebaseRemoteConfigHostApi.activate.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_activate(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    gboolean return_value);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_activate:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.activate.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_activate(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_set_config_settings:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 *
 * Responds to FirebaseRemoteConfigHostApi.setConfigSettings.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_set_config_settings(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_set_config_settings:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.setConfigSettings.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_set_config_settings(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_set_defaults:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 *
 * Responds to FirebaseRemoteConfigHostApi.setDefaults.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_set_defaults(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_set_defaults:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.setDefaults.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_set_defaults(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_ensure_initialized:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 *
 * Responds to FirebaseRemoteConfigHostApi.ensureInitialized.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_ensure_initialized(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_ensure_initialized:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.ensureInitialized.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_ensure_initialized(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_set_custom_signals:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 *
 * Responds to FirebaseRemoteConfigHostApi.setCustomSignals.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_set_custom_signals(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_set_custom_signals:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.setCustomSignals.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_set_custom_signals(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_get_all:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FirebaseRemoteConfigHostApi.getAll.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_get_all(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    FlValue* return_value);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_get_all:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.getAll.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_get_all(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_get_properties:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FirebaseRemoteConfigHostApi.getProperties.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_get_properties(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    FlValue* return_value);

/**
 * firebase_remote_config_firebase_remote_config_host_api_respond_error_get_properties:
 * @response_handle: a
 * #FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FirebaseRemoteConfigHostApi.getProperties.
 */
void firebase_remote_config_firebase_remote_config_host_api_respond_error_get_properties(
    FirebaseRemoteConfigFirebaseRemoteConfigHostApiResponseHandle*
        response_handle,
    const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
