name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.
resolution: workspace

environment:
  sdk: '^3.6.0'
  flutter: '>=3.27.0'

dependencies:
  cloud_functions: ^6.3.0
  firebase_core: ^4.8.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
