// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import 'api.dart';
import 'content.dart';
import 'error.dart';

/// Represents the available voice options for speech synthesis.
enum Voices {
  // ignore: public_member_api_docs, constant_identifier_names
  Aoede('Aoede'),

  // ignore: public_member_api_docs, constant_identifier_names
  Charon('Charon'),

  // ignore: public_member_api_docs, constant_identifier_names
  Fenrir('Fenrir'),

  // ignore: public_member_api_docs, constant_identifier_names
  Kore('Kore'),

  // ignore: public_member_api_docs, constant_identifier_names
  Puck('Puck');

  const Voices(this._jsonString);
  final String _jsonString;

  // ignore: public_member_api_docs
  String toJson() => _jsonString;
}

/// Configures speech synthesis settings.
class SpeechConfig {
  /// Creates a [SpeechConfig] instance.
  ///
  /// [voice] (optional): The desired voice for speech synthesis.
  SpeechConfig({this.voice});

  /// The voice to use for speech synthesis.
  final Voices? voice;
  // ignore: public_member_api_docs
  Map<String, Object?> toJson() => {
        if (voice != null)
          'voice_config': {
            'prebuilt_voice_config': {'voice_name': voice!.toJson()}
          }
      }; // Or null
}

/// Represents the available response modalities.
enum ResponseModalities {
  /// Unspecified response modality.
  unspecified('MODALITY_UNSPECIFIED'),

  /// Text response modality.
  text('TEXT'),

  /// Image response modality.
  image('IMAGE'),

  /// Audio response modality.
  audio('AUDIO');

  const ResponseModalities(this._jsonString);
  final String _jsonString;

  /// Convert to json format
  String toJson() => _jsonString;
}

/// Configures live generation settings.
final class LiveGenerationConfig extends BaseGenerationConfig {
  // ignore: public_member_api_docs
  LiveGenerationConfig({
    this.speechConfig,
    this.responseModalities,
    super.candidateCount,
    super.maxOutputTokens,
    super.temperature,
    super.topP,
    super.topK,
  });

  /// The speech configuration.
  final SpeechConfig? speechConfig;

  /// The list of desired response modalities.
  final List<ResponseModalities>? responseModalities;

  @override
  Map<String, Object?> toJson() => {
        ...super.toJson(),
        if (speechConfig case final speechConfig?)
          'speechConfig': speechConfig.toJson(),
        if (responseModalities case final responseModalities?)
          'responseModalities':
              responseModalities.map((modality) => modality.toJson()).toList(),
      };
}

/// An abstract class representing a message received from a live server.
///
/// This class serves as a base for different types of server messages,
/// such as content updates, tool calls, and tool call cancellations.
/// Subclasses should implement specific message types.
abstract class LiveServerMessage {}

/// A message indicating that the live server setup is complete.
///
/// This message signals that the initial connection and setup process
/// with the live server has finished successfully.
class LiveServerSetupComplete implements LiveServerMessage {}

/// Represents content generated by the model in a live stream.
class LiveServerContent implements LiveServerMessage {
  /// Creates a [LiveServerContent] instance.
  ///
  /// [modelTurn] (optional): The content generated by the model.
  /// [turnComplete] (optional): Indicates if the turn is complete.
  /// [interrupted] (optional): Indicates if the generation was interrupted.
  LiveServerContent({this.modelTurn, this.turnComplete, this.interrupted});

  /// The content generated by the model.
  final Content? modelTurn;

  /// Indicates if the turn is complete.
  final bool? turnComplete;

  /// Indicates if the generation was interrupted.
  final bool? interrupted;
}

/// Represents a tool call in a live stream.
class LiveServerToolCall implements LiveServerMessage {
  /// Creates a [LiveServerToolCall] instance.
  ///
  /// [functionCalls] (optional): The list of function calls.
  LiveServerToolCall({this.functionCalls});

  /// The list of function calls.
  final List<FunctionCall>? functionCalls;
}

/// Represents a tool call cancellation in a live stream.
class LiveServerToolCallCancellation implements LiveServerMessage {
  /// Creates a [LiveServerToolCallCancellation] instance.
  ///
  /// [functionIds] (optional): The list of function IDs to cancel.
  LiveServerToolCallCancellation({this.functionIds});

  /// The list of function IDs to cancel.
  final List<String>? functionIds;
}

/// Represents realtime input from the client in a live stream.
class LiveClientRealtimeInput {
  /// Creates a [LiveClientRealtimeInput] instance.
  ///
  /// [mediaChunks] (optional): The list of media chunks.
  LiveClientRealtimeInput({this.mediaChunks});

  /// The list of media chunks.
  final List<InlineDataPart>? mediaChunks;

  // ignore: public_member_api_docs
  Map<String, dynamic> toJson() => {
        'realtime_input': {
          'media_chunks':
              mediaChunks?.map((e) => e.toMediaChunkJson()).toList(),
        },
      };
}

/// Represents content from the client in a live stream.
class LiveClientContent {
  /// Creates a [LiveClientContent] instance.
  ///
  /// [turns] (optional): The list of content turns from the client.
  /// [turnComplete] (optional): Indicates if the turn is complete.
  LiveClientContent({this.turns, this.turnComplete});

  /// The list of content turns from the client.
  final List<Content>? turns;

  /// Indicates if the turn is complete.
  final bool? turnComplete;

  // ignore: public_member_api_docs
  Map<String, dynamic> toJson() => {
        'client_content': {
          'turns': turns?.map((e) => e.toJson()).toList(),
          'turn_complete': turnComplete,
        }
      };
}

/// Represents a tool response from the client in a live stream.
class LiveClientToolResponse {
  /// Creates a [LiveClientToolResponse] instance.
  ///
  /// [functionResponses] (optional): The list of function responses.
  LiveClientToolResponse({this.functionResponses});

  /// The list of function responses.
  final List<FunctionResponse>? functionResponses;
  // ignore: public_member_api_docs
  Map<String, dynamic> toJson() => {
        'functionResponses': functionResponses?.map((e) => e.toJson()).toList(),
      };
}

/// Parses a JSON object received from the live server into a [LiveServerMessage].
///
/// This function handles different types of server messages, including:
/// - Error messages, which result in a [VertexAIException] being thrown.
/// - `serverContent` messages containing model-generated content.
/// - `toolCall` messages indicating function calls requested by the model.
/// - `toolCallCancellation` messages to cancel pending function calls.
/// - `setupComplete` messages signaling the completion of the server setup.
///
/// If the JSON object does not match any of the expected formats, an
/// [VertexAISdkException] is thrown.
///
/// Example:
/// ```dart
/// final jsonObject = {
///   'serverContent': {
///     'modelTurn': {
///       'parts': [
///         {'text': 'Hello, world!'}
///       ]
///     },
///     'turnComplete': true,
///   }
/// };
/// final message = parseServerMessage(jsonObject);
/// if (message is LiveServerContent) {
///   print('Received server content: ${message.modelTurn}');
/// }
/// ```
///
/// Throws:
/// - [VertexAIException]: If the JSON object contains an error message.
/// - [VertexAISdkException]: If the JSON object does not match any expected format.
///
/// Parameters:
/// - [jsonObject]: The JSON object received from the live server.
///
/// Returns:
/// - A [LiveServerMessage] object representing the parsed message.
LiveServerMessage parseServerMessage(Object jsonObject) {
  if (jsonObject case {'error': final Object error}) {
    throw parseError(error);
  }

  Map<String, dynamic> json = jsonObject as Map<String, dynamic>;

  if (json.containsKey('serverContent')) {
    final serverContentJson = json['serverContent'] as Map<String, dynamic>;
    Content? modelTurn;
    if (serverContentJson.containsKey('modelTurn')) {
      modelTurn = parseContent(serverContentJson['modelTurn']);
    }
    bool? turnComplete;
    if (serverContentJson.containsKey('turnComplete')) {
      turnComplete = serverContentJson['turnComplete'] as bool;
    }
    return LiveServerContent(modelTurn: modelTurn, turnComplete: turnComplete);
  } else if (json.containsKey('toolCall')) {
    final toolContentJson = json['toolCall'] as Map<String, dynamic>;
    List<FunctionCall> functionCalls = [];
    if (toolContentJson.containsKey('functionCalls')) {
      final functionCallJsons =
          toolContentJson['functionCalls']! as List<dynamic>;
      for (final functionCallJson in functionCallJsons) {
        var functionCall =
            parsePart({'functionCall': functionCallJson}) as FunctionCall;
        functionCalls.add(functionCall);
      }
    }

    return LiveServerToolCall(functionCalls: functionCalls);
  } else if (json.containsKey('toolCallCancellation')) {
    final toolCancelJson =
        json['toolCallCancellation'] as Map<String, List<String>>;
    return LiveServerToolCallCancellation(functionIds: toolCancelJson['ids']);
  } else if (json.containsKey('setupComplete')) {
    return LiveServerSetupComplete();
  } else {
    throw unhandledFormat('LiveServerMessage', json);
  }
}
