module.exports = [
  {
    name: 'AdMob (Deprecated)',
    pub: 'firebase_admob',
    firebase: 'admob',
    documentation: '',
    support: {
      web: false,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'Analytics',
    pub: 'firebase_analytics',
    firebase: 'analytics',
    documentation: 'https://firebase.flutter.dev/docs/analytics/overview',
    support: {
      web: true,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'Authentication',
    pub: 'firebase_auth',
    firebase: 'auth',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/auth/overview',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Cloud Firestore',
    pub: 'cloud_firestore',
    firebase: 'firestore',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/firestore/overview',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Cloud Functions',
    pub: 'cloud_functions',
    firebase: 'functions',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/functions/overview',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Cloud Messaging',
    pub: 'firebase_messaging',
    firebase: 'cloud-messaging',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/messaging/overview',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Cloud Storage',
    pub: 'firebase_storage',
    firebase: 'storage',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/storage/overview',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Core',
    pub: 'firebase_core',
    firebase: '',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/core/usage',
    support: {
      web: true,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Crashlytics',
    pub: 'firebase_crashlytics',
    firebase: 'crashlytics',
    production: true,
    documentation: 'https://firebase.flutter.dev/docs/crashlytics/overview',
    support: {
      web: false,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Realtime Database',
    pub: 'firebase_database',
    firebase: 'database',
    documentation: 'https://firebase.flutter.dev/docs/database/overview',
    support: {
      web: false,
      mobile: true,
      macos: true,
    },
  },
  {
    name: 'Dynamic Links',
    pub: 'firebase_dynamic_links',
    firebase: 'dynamic-links',
    documentation: '',
    support: {
      web: false,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'In-App Messaging',
    pub: 'firebase_in_app_messaging',
    firebase: 'in-app-messaging',
    documentation: '',
    support: {
      web: false,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'ML Kit Vision',
    pub: 'firebase_ml_vision',
    firebase: 'ml-kit',
    documentation: '',
    support: {
      web: false,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'Performance Monitoring',
    pub: 'firebase_performance',
    firebase: 'performance',
    documentation: 'https://firebase.flutter.dev/docs/performance/overview',
    support: {
      web: false,
      mobile: true,
      macos: false,
    },
  },
  {
    name: 'Remote Config',
    pub: 'firebase_remote_config',
    firebase: 'remote-config',
    documentation: 'https://firebase.flutter.dev/docs/remote-config/overview',
    support: {
      web: false,
      mobile: true,
      macos: true,
    },
  },
];
