name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.
resolution: workspace

environment:
  sdk: '^3.6.0'
  flutter: '>=3.27.0'

dependencies:
  cloud_firestore: ^6.4.0
  firebase_core: ^4.8.0
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
