name: build-linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linux
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**/example/**'
      - '!**/example/integration_test/**'
      - '**/flutterfire_ui/**'
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**/example/**'
      - '!**/example/integration_test/**'
      - '**/flutterfire_ui/**'
      - '**.md'

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: "Install Linux desktop build dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-:hash:"
      - uses: bluefireteam/melos-action@705015c3d2bc4ab94201ac24accb2bbe070cf533
        with:
          run-bootstrap: false
          melos-version: '3.0.0'
      - name: "Bootstrap package"
        run: melos bootstrap --scope "firebase_core*"
      - name: "Build Linux (Release)"
        run: cd packages/firebase_core/firebase_core/example && flutter build linux --release
